
using System;
using System.Collections.Generic;
using System.Data.Linq;
using System.IO;
using System.Linq;
using System.Windows.Forms;

namespace WinFormsDataBinding {
    static class Program 
    {
        // The following sample assumes that you installed the DATA sample 
        // project and that Northwind.MDF is in that Data directory.
        private readonly static string dbPath = Path.GetFullPath(Path.Combine(Application.StartupPath, @"..\..\..\Data\NORTHWND.MDF"));
        private const string sqlServerInstance = @".\SQLEXPRESS";
       // public readonly static string connString = "AttachDBFileName='" + dbPath + "';Server='" + sqlServerInstance + "';user instance=true;Integrated Security=SSPI;Connection Timeout=60";

        // public readonly static string connectionString="metadata=res://*/NORTHWND.csdl|res://*/MovieReviews.ssdl|res://*/NORTHWND.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=(LocalDB)\v11.0;attachdbfilename=E:\try\NORTHWND.MDF;integrated security=True;connect timeout=30;MultipleActiveResultSets=True;App=EntityFramework&quot;" providerName="System.Data.EntityClient";

        public readonly static string connString = "Server=10.10.10.10;Database=Northwind;uid=sa;pwd=P@ssw0rd123;";
            //providerName="System.Data.SqlClient"

        //Additionally the Northwind.cs file has been modified from that generated by SQLMetal
        //to include override ToString method on the Employee entity, this allows the DataGridView's
        //ReportsToEmployee column to display a reasonable value.
        [STAThread]
        static void Main() {
            Application.EnableVisualStyles();
            Application.Run(new EmployeeForm());
        }
    }
}